/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package snake;

import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Timer;
import static snake.MainFrame.frame;

/**
 *
 * @author Kuba
 */
public class SnakePanel extends javax.swing.JPanel implements ActionListener {

    /**
     * Creates new form SnakePanel2
     */
    public SnakePanel() {
        initComponents();
        logic.initSnake();
        frame.addKeyListener(logic);
        timer = new Timer(350, this);
        timer.start();
    }

    SnakeLogic logic = new SnakeLogic();
    static Timer timer;
    private Color snakeColor = Color.black;
    private Color backgroundColor = Color.white;
    private Color fruitColor = Color.red;
    private final int SIZE = 50;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void drawFruit(Graphics2D g2d) {
        int r = logic.getFruitPosition().getR();
        int c = logic.getFruitPosition().getC();
        g2d.setColor(fruitColor);
        g2d.fillRect(c * SIZE, r * SIZE, SIZE - 2, SIZE - 2);
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        logic.updatePosition();

        repaint();
    }

    @Override
    public void paintComponent(Graphics g) {
        Graphics2D g2d = (Graphics2D) g;

        repaintBackground(g2d);
        drawSnake(g2d);

        if (logic.isAte()) {
            logic.generateFruit();
            logic.setAte(false);
        }

        drawFruit(g2d);

        if (logic.isGameOver()) {
            gameOver(g);
        }

    }

    private void gameOver(Graphics g) {
        g.setColor(Color.WHITE);
        g.fillRect(0, 0, 600, 700);
        g.setFont(new Font("TimesRoman", Font.PLAIN, 40));
        g.setColor(Color.BLACK);
        g.drawString("   GAME OVER!!!", 130, 180);
        g.drawString("Zdobyłeś "+logic.getPoints()+" punktów!", 130, 280);
        g.setFont(new Font("TimesRoman", Font.PLAIN, 30));
        g.drawString("Kliknij ,,enter'' aby ", 130, 480);
        g.drawString("rozpocząć od nowa", 130, 530);
        logic.getSnake().length = 0;
        logic.getSnake().getPosition().clear();
        logic.initSnake();
        logic.setGameOver(false);
        logic.setPoints(0);
        timer.stop();
    }

    private void repaintBackground(Graphics2D g2d) {
        g2d.setColor(backgroundColor);
        g2d.fillRect(0, 0, this.getWidth(), this.getHeight());
    }

    private void drawSnake(Graphics2D g2d) {
        int r;
        int c;
        g2d.setColor(snakeColor);
        for (int i = 0; i < logic.getSnake().length; i++) {
            r = logic.getSnake().getPosition().get(i).getR();
            c = logic.getSnake().getPosition().get(i).getC();
            g2d.fillRect(c * SIZE, r * SIZE, SIZE - 2, SIZE - 2);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
